version: "3.7"
services:

  tracardi-api-old:
    image: tracardi/tracardi-api:0.7.3
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      LOGGING_LEVEL: info
    ports:
      - 18686:80
    depends_on:
      - redis
      - elasticsearch

  tracardi-gui-old:
    image: tracardi/tracardi-gui:0.7.3
    environment:
      API_URL: http://tracardi-api:8686
    ports:
      - 18787:80
    depends_on:
      - tracardi-api

  tracardi-api:
    image: tracardi/tracardi-api:0.7.4
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      LOGGING_LEVEL: info
    ports:
      - 8686:80
    depends_on:
      - redis
      - elasticsearch

  tracardi-gui:
    image: tracardi/tracardi-gui:0.7.4
    environment:
      API_URL: http://tracardi-api:8686
    ports:
      - 8787:80
    depends_on:
      - tracardi-api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      xpack.security.enabled: "false"
      cluster.name: contextElasticSearch
    ports:
      - 9200:9200

  redis:
    image: redis
    ports:
      - 6379:6379
