site_name: Tracardi Documentation
site_description: Open-source Data Platform
site_url: https://docs.tracardi.com
dev_addr: "0.0.0.0:8585"
markdown_extensions:
  - admonition
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
#plugins:
#  - git-revision-date-localized:
#      enable_creation_date: true
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
  #    - navigation.tabs
  palette:
    - primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tracardi
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/tracardi
    - icon: fontawesome/brands/github
      link: https://github.com/Tracardi/tracardi
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@tracardi
copyright: Copyright &copy; 2020 - 2021 Tracardi
repo_url: https://github.com/tracardi/tracardi-api
repo_name: tracardi/tracardi-api
nav:
  - index.md
  - what_is_tracardi.md
  - Getting started:
      - getting_started/index.md
      - getting_started/architecture.md
      - getting_started/core_definitions.md
      - getting_started/data_flow.md
  - Installation:
      - installation/index.md
      - installation/best_practises.md
      - installation/upgrades.md
      - Docker:
          - installation/docker/index.md
          - installation/docker/building_docker_image.md
      - Source:
          - installation/source/index.md
      - Production:
          - installation/production/index.md
          - installation/production/services.md
          - installation/production/k8s/index.md
          - installation/staging/index.md
      - Commercial:
          - installation/commercial/index.md

  - Configuration:
      - configuration/tracardi_configuration.md
      - configuration/best_practises.md
      - Elasticsearch:
          - configuration/elasticsearch/connecting_elasticsearch_cluster.md
          - configuration/elasticsearch/elastic_authentication.md
          - configuration/elasticsearch/elastic_max_connections.md
          - configuration/elasticsearch/elastic_sniffing.md
      - configuration/tracardi_ssl.md
  - Integration:
      - API:
          - integration/api/api-integration.md
          - integration/api/mobile-integration.md
          - integration/api/tracker-response.md
          - integration/api/errors.md
      - Javascript:
          - integration/js/index.md
          - integration/js/context.md
          - integration/js/options.md
          - integration/js/response.md
          - integration/js/advanced.md
      - Redirected Links:
          - integration/redirect/index.md
  - upgrade.md
  - trouble/index.md
  - Running:
      - running/index.md
      - Traffic:
          - traffic/inbound/index.md
          - traffic/outbound/index.md
      - Events:
          - events/index.md
          - getting_started/tracking.md
          - events/event_tracking.md
          - events/event_validation.md
          - events/synchronization.md
          - Event traits schema:
              - events/event_traits_schema.md
          - Internal event types:
              - events/internal/index.md
              - events/internal/sign-up.md
              - events/internal/basket-viewed.md
              - events/internal/checkout-completed.md
              - events/internal/checkout-started.md
              - events/internal/checkout-status.md
              - events/internal/delivery-info-entered.md
              - events/internal/identification.md
              - events/internal/loyalty-card-added.md
              - events/internal/loyalty-card-removed.md
              - events/internal/order-completed.md
              - events/internal/order-started.md
              - events/internal/page-print.md
              - events/internal/page-view.md
              - events/internal/payment-info-entered.md
              - events/internal/product-added-to-basket.md
              - events/internal/product-clicked.md
              - events/internal/product-details-page-view.md
              - events/internal/product-removed-from-basket.md
              - events/internal/product-reviewed.md
              - events/internal/product-search-result.md
              - events/internal/product-shared.md
              - events/internal/profile-archived.md
              - events/internal/profile-created.md
              - events/internal/profile-inactive.md
              - events/internal/promotion-clicked.md
              - events/internal/promotion-viewed.md
              - events/internal/screen-view.md
              - events/internal/search.md
              - events/internal/session-closed.md
              - events/internal/session-opened.md
              - events/internal/sign-in.md

      - Profiles:
          - profiles/index.md
          - profiles/profile_merging.md
          - profiles/profile_segmentation.md
      - Resources:
          - resources/index.md
          - Documentation:
              - resources/elastic_email_resource.md
              - resources/matomo_resource.md
              - resources/novu_resource.md
              - resources/redis_resource.md
              - resources/activecampaign_resource.md
              - resources/airtable_resource.md
              - resources/amplitude_resource.md
              - resources/aws_resource.md
              - resources/civi_resource.md
              - resources/fullcontact_resource.md
              - resources/hubspot_resource.md
              - resources/mailchimp_resource.md
              - resources/mautic_resource.md
              - resources/meaningcloud_resource.md
              - resources/microservice_resource.md
              - resources/mongo_resource.md
              - resources/mysql_resource.md
              - resources/postgresql_resource.md
              - resources/pushover_resource.md
              - resources/rabbitmq_resource.md
              - resources/scheduler_resource.md
              - resources/sendgrid_resource.md
              - resources/influxdb_resource.md
              - resources/mixpanel_resource.md
              - resources/mqtt_resource.md
              - resources/salesforce_resource.md
              - resources/zapier_resource.md
              - resources/chatwoot_resource.md
              - resources/elasticsearch_resource.md
              - resources/sms77_resource.md
              - resources/twitter_resource.md
              - resources/discord_resource.md
              - resources/ga4_tracker_resource.md
              - resources/github_resource.md
              - resources/ua3_tracker_resource.md

      - Workflows:
          - flow/index.md
          - Actions:
              - flow/actions/index.md
              - flow/actions/if_action.md
              - flow/actions/elastic_email_contact_action.md
              - flow/actions/elastic_email_transactional_action.md
              - flow/actions/detect_client_agent_action.md
              - flow/actions/inject_action.md
              - flow/actions/event_scheduler_action.md
              - flow/actions/get_prev_event_action.md
              - flow/actions/get_prev_session_action.md
              - flow/actions/new_event_action.md
              - flow/actions/new_visit_action.md
              - flow/actions/event_counter_action.md
              - flow/actions/condition_set_action.md
              - flow/actions/count_by_query_string_action.md
              - flow/actions/reshape_payload_action.md
              - flow/actions/assign_profile_id_action.md
              - flow/actions/template_action.md
              - flow/actions/append_remove_trait_action.md
              - flow/actions/start_action.md
              - flow/actions/base64_decode.md
              - flow/actions/base64_encode.md
              - flow/actions/data_exists_action.md
              - flow/actions/profile_inject_action.md
              - flow/actions/sort_array_action.md
              - flow/actions/sorted_dict_action.md
              - flow/actions/string_join_action.md
              - flow/actions/string_similarity_action.md
              - flow/actions/twitter_tweet_action.md
              - flow/actions/geo/geo_ip_locator.md
              - flow/actions/sms77/sms77_send_sms_plugin.md
              - flow/actions/calculator_action.md
              - flow/actions/random_element_action.md
              - flow/actions/assign_condition_result_action.md
              - flow/actions/reduce_array_action.md
              - flow/actions/password_generator_action.md
              - flow/actions/contains_pattern_action.md
              - flow/actions/google_translate_action.md
              - flow/actions/join_output_payloads.md
              - flow/actions/limiter_action.md
              - flow/actions/marge_data_action.md
              - Operations:
                  - flow/actions/update_profile_action.md
                  - flow/actions/merge_profiles_action.md
                  - flow/actions/segment_profiles_action.md
                  - flow/actions/new_profile_action.md
                  - flow/actions/update_event_action.md
                  - flow/actions/update_session_action.md
              - Stats:
                  - flow/actions/increment_action.md
                  - flow/actions/decrement_action.md
                  - flow/actions/increase_views_action.md
                  - flow/actions/increase_visits_action.md
                  - flow/actions/key_counter_action.md
              - Connectors:
                  - flow/actions/zapier_webhook_action.md
                  - flow/actions/smtp_connector_action.md
                  - flow/actions/remote_call_action.md
                  - flow/actions/fullcontact_webhook_action.md
                  - flow/actions/rabbit_publisher_action.md
                  - flow/actions/send_pushover_msg_action.md
                  - flow/actions/weather_action.md
                  - flow/actions/oauth2_token_action.md
                  - flow/actions/send_to_influx_db_action.md
                  - flow/actions/rabbitmq_action.md
                  - flow/actions/fetch_from_airtable_action.md
                  - flow/actions/fetch_from_influxdb_action.md
                  - flow/actions/elasticsearch_query_action.md
                  - flow/password_generator_action.md
                  - flow/actions/contains_string_action.md
                  - flow/actions/ends_with_action.md
                  - flow/actions/starts_with_action.md
                  - flow/actions/weekdays_checker_action.md
                  - Databases:
                      - flow/actions/mongo_query_action.md
                      - flow/actions/mysql_connector_action.md
                      - flow/actions/send_to_airtable_action.md
                  - Messagers:
                      - flow/actions/send_to_slack_channel_action.md
                      - flow/actions/discord_webhook_action.md
                      - flow/actions/telegram/telegram_post_plugin.md
                  - Novu:
                      - flow/actions/novu_plugin_action.md
                  - Elastic mail:
                      - flow/actions/elastic_email_bulk_action.md
                      - flow/actions/elastic_email_change_contact_status_action.md
                      - flow/actions/elastic_email_contact_add_action.md
                  - Trello:
                      - flow/actions/trello/add_trello_card_action.md
                      - flow/actions/trello/add_trello_member_action.md
                      - flow/actions/trello/delete_trello_card_action.md
                      - flow/actions/trello/move_trello_card_action.md
                  - Mautic:
                      - flow/actions/add_mautic_contact_action.md
                      - flow/actions/fetch_mautic_contact_by_email_action.md
                      - flow/actions/fetch_mautic_contact_by_id_action.md
                      - flow/actions/edit_points_in_mautic_action.md
                      - flow/actions/edit_segment_in_mautic_action.md
                  - Mixpanel:
                      - flow/actions/fetch_mixpanel_funnel_action.md
                      - flow/actions/send_to_mixpanel_action.md
                  - Mailchimp:
                      - flow/actions/mailchimp_transactional_action.md
                      - flow/actions/mailchimp_add_to_audience_action.md
                      - flow/actions/mailchimp_remove_from_audience_action.md
                  - Sales force:
                      - flow/actions/send_to_data_extension_action.md
                  - Active campaign:
                      - flow/actions/fetch_ac_contact_by_email_action.md
                      - flow/actions/add_active_campaign_contact_action.md
                  - Hubspot:
                      - flow/actions/hubspot_get_company_action.md
                      - flow/actions/hubspot_get_contact_action.md
                      - flow/actions/hubspot_update_company_action.md
                      - flow/actions/hubspot/hubspot_add_company_action.md
                      - flow/actions/hubspot/hubspot_add_contact_action.md
                      - flow/actions/hubspot_update_contact_action.md
                  - Sendgrid:
                      - flow/actions/sendgrid_add_contact_to_list.md
                      - flow/actions/sendgrid_add_to_global_suppression.md
                      - flow/actions/sendgrid_send_email.md
                  - Google:
                      - flow/actions/google_event_tracker_action.md
                      - flow/actions/google_v4_event_tracker_action.md
                  - Matomo:
                      - flow/actions/matomo/register_event.md


              - Regex:
                  - flow/actions/regex/regex_validator_action.md
                  - flow/actions/regex/regex_match.md
                  - flow/actions/regex/regex_replace_action.md

              - Locations:
                  - flow/actions/geo_ip_locator.md

              - Time:
                  - flow/actions/day_night_split_action.md
                  - flow/actions/local_time_span_action.md
                  - flow/actions/calculate_time_difference_action.md
                  - flow/actions/today_action.md

              - Processing:
                  - flow/actions/url_parser_action.md
                  - flow/actions/string_splitter_action.md
                  - flow/actions/string_properties_action.md
                  - flow/actions/profile_segment.md
                  - flow/actions/mapping_action.md

              - Validators:
                  - flow/actions/validate_with_json_schema_action.md
                  - flow/actions/string_validator_action.md
                  - flow/actions/field_type_action.md

              - Machine Learning:
                  - flow/actions/text_classification_action.md
                  - flow/actions/lang_detection_action.md
                  - flow/actions/sentiment_analysis_action.md
                  - flow/actions/corporate_reputation_action.md
                  - flow/actions/deep_categorization_action.md
                  - flow/actions/summarization_action.md
                  - flow/actions/topics_extraction_action.md

              - UX:
                  - flow/actions/question_popup_action.md
                  - flow/actions/rating_popup_action.md
                  - flow/actions/contact_popup_action.md
                  - flow/actions/generic_uix_action.md
                  - Chat:
                      - flow/actions/chatwoot_widget_action.md
                      - flow/actions/intercom_widget_action.md
                      - flow/actions/livechat_widget_action.md
                      - flow/actions/zendesk_widget_action.md

              - Memory:
                  - flow/actions/write_to_memory_action.md
                  - flow/actions/read_from_memory_action.md
                  - flow/actions/memory/payload_memory_collector.md

              - Consents:
                  - flow/actions/add_consents_action.md
                  - flow/actions/require_consents_action.md

              - Errors:
                  - flow/actions/log_message_action.md
                  - flow/actions/throw_error_action.md



      - Filtering:
          - running/filtering.md
      - Notations:
          - notations/dot_notation.md
          - notations/logic_notation.md
          - notations/templates.md
          - notations/object_template.md

      - Q&A:
          - qa/how_to_copy_data_from_event_to_profile.md
          - qa/how_to_replace_a_profile_in_workflow.md
          - qa/how_to_use_own_profile_id.md
          - qa/how_to_use_workflow_editor.md
          - qa/utms.md
          - qa/can_tracardi_import_data_from_csv.md
          - qa/how_many_records_can_tracardi_store.md
          - qa/how_to_fix_import_pending.md
          - qa/how_to_fix_webhook_validation_error.md
          - qa/how_to_get_javascript_to_put_on_page.md
          - qa/how_to_integrate_with_webhook.md
          - qa/how_to_pass_profile_id_from_domain_to_domain.md
          - qa/how_to_quickly_copy_data_from_node_to_node_in_wf.md
          - qa/how_tracardi_loads_profile.md
          - qa/other_qa.md
          - qa/who_is_tracardi_for.md

  - api/index.md
  - Developers:
      - Development environmet set-up:
          - development/react_env.md
          - development/python_env.md
      - Mirco frontend apps developement:
          - development/micro_frontend.md
      - Plugins:
          - plugins/index.md
          - Tutorials:
              - plugins/tutorial/part1.md
              - plugins/tutorial/part2.md
              - plugins/tutorial/part3.md
          - plugins/forms/list_of_field_types.md

  - support_us.md
  - attribution.md
  - software_license.md
  - documentation_license.md

